[package]
name = "wadray"
version = "0.4.0"
cairo-version = "2.7.0"
edition = "2024_07"
authors = ["Lindy Labs"]
description = "Fixed-point decimal numbers for Cairo"
readme = "README.md"
repository = "https://github.com/lindy-labs/wadray"
license-file = "LICENSE"
keywords = ["fixed-point", "wad", "ray", "cairo", "starknet"]

[dependencies]
starknet = ">= 2.7.0"

[dev-dependencies]
snforge_std = { git = "https://github.com/foundry-rs/starknet-foundry.git", tag = "v0.27.0" }

[lib]
sierra-text = true

[tool.fmt]
sort-module-level-items = true
max-line-length = 120

[scripts]
test = "snforge test"

# for formal verification workflow
[profile.fv]
sierra-replace-ids = true
sierra-text = true
inlining-strategy = "avoid"
