[package]
name = "wadray"
version = "0.2.0"
cairo-version = "2.4.0"
authors = ["Lindy Labs"]
description = "Fixed-point decimal numbers for Cairo"
readme = "README.md"
repository = "https://github.com/lindy-labs/wadray"
license-file = "LICENSE"
keywords = ["fixed-point", "wad", "ray", "cairo", "starknet"]

[dependencies]
starknet = ">= 2.4"

[dev-dependencies]
snforge_std = { git = "https://github.com/foundry-rs/starknet-foundry.git", tag = "v0.14.0" }

[lib]

[tool.fmt]
sort-module-level-items = true
max-line-length = 120

[scripts]
test = "snforge test"
