[package]
name = "cairo_wadray"
version = "0.1.0"

[dependencies]
starknet = "2.3.1"
snforge_std = { git = "https://github.com/foundry-rs/starknet-foundry.git", tag = "v0.11.0" }

[tool.fmt]
sort-module-level-items = true
max-line-length = 120

[scripts]
test = "snforge test"