[package]
name = "wadray"
version = "0.6.1"
cairo-version = "2.11.4"
edition = "2024_07"
authors = ["Lindy Labs"]
description = "Fixed-point decimal numbers for Cairo"
readme = "README.md"
repository = "https://github.com/lindy-labs/wadray"
license-file = "LICENSE"
keywords = ["fixed-point", "wad", "ray", "cairo", "starknet"]

[dependencies]
starknet = ">= 2.11.4"

[dev-dependencies]
snforge_std = ">= 0.41.0"
assert_macros = ">= 2.11.4"

[lib]
sierra-text = true

[tool.fmt]
sort-module-level-items = true
max-line-length = 120

[tool.scarb]
allow-prebuilt-plugins = ["snforge_std"]

[scripts]
test = "snforge test"

# for formal verification workflow
[profile.fv]
sierra-replace-ids = true
sierra-text = true
inlining-strategy = "avoid"
