name: Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: software-mansion/setup-scarb@v1
        with:
          scarb-version: "2.6.3"
      - run: scarb fmt --check
      - run: scarb build

      - name: Install Universal-Sierra-Compiler
        run: curl -L https://raw.githubusercontent.com/software-mansion/universal-sierra-compiler/master/scripts/install.sh | sh -s -- v2.0.0

      - uses: foundry-rs/setup-snfoundry@v2
        with:
          starknet-foundry-version: "0.19.0"
      - run: snforge test
